insert into productos(nombre,precio,create_at) values ('Panasonic',800,NOW());
insert into productos(nombre,precio,create_at) values ('Sony',850,NOW());
insert into productos(nombre,precio,create_at) values ('Apple',670,NOW());
insert into productos(nombre,precio,create_at) values ('HP',600,NOW());
insert into productos(nombre,precio,create_at) values ('Adidas',500,NOW());
insert into productos(nombre,precio,create_at) values ('Nike',400,NOW());
insert into productos(nombre,precio,create_at) values ('Reebook',10,NOW());
insert into productos(nombre,precio,create_at) values ('NewBalance',80,NOW());
insert into productos(nombre,precio,create_at) values ('Bianchi',300,NOW());